# Generated by Django 3.0.9 on 2021-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200817_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('contact_no', models.CharField(default='', max_length=50)),
                ('desc', models.IntegerField(default='', max_length=500)),
            ],
        ),
    ]
